blogaggregator/blogaggregator/user/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from flask.ext.login import UserMixin

from blogaggregator.extensions import bcrypt
from blogaggregator.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)


class Role(SurrogatePK, Model):
    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = ReferenceCol('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Role({name})>'.format(name=self.name)

class User(UserMixin, SurrogatePK, Model):

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    
    atomfeed = Column(db.String(2000), nullable=True)
    atomposts= Column(db.Integer(), default=0)  
    
    #set last atom date to the UTC time stamp 0, (1970) so we can check for new posts
    latest_atom = Column(db.DateTime, default=dt.datetime.utcfromtimestamp(0),nullable=False)
    
    # Latest update, either post, atom, or comment made on a post of this user
    latest_update = Column(db.DateTime, default=dt.datetime.utcfromtimestamp(0),nullable=False)

    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)
        

class Post(SurrogatePK, Model):
    __tablename__ = 'posts'
    user_id = ReferenceCol('users', nullable=False)
    user = relationship('User', backref='posts')
    
    title = Column(db.String(300), nullable=True, default = "Title")
    content = Column(db.Text(), nullable=False)
    summary = Column(db.Text(), nullable=False)
    
    link = Column(db.String(2000), nullable=True)
    atomuuid = Column(db.String(120), nullable=False)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    edited_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    
    #number of comments
    comment_count = Column(db.Integer(), default=0)  
    
    
class Comment(SurrogatePK, Model):
    __tablename__ = 'comments'
    post_id = ReferenceCol('posts', nullable=False)
    post = relationship('Post', backref='comments')
    
    user_id = ReferenceCol('users', nullable=False)
    user = relationship('User', backref='comments')
    
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    edited_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    
    content = Column(db.Text(), nullable=False)
    
    
    
    

blogaggregator/blogaggregator/user/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField, TextAreaField
from wtforms.fields.html5 import URLField
from wtforms.validators import DataRequired, Email, EqualTo, Length, url
from blogaggregator.utils import good_feed
from flask.ext.login import current_user


from .models import User

class RegisterForm(Form):
    username = TextField('Username',
                    validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email',
                    validators=[DataRequired(), Email(), Length(min=6, max=40)])
    atomfeed = URLField('Atom Feed')
    registrationkey = TextField('Registration Key',validators=[DataRequired()])
    password = PasswordField('Password',
                                validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False

        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        if self.registrationkey.data != "DS106TestKey":
            self.registrationkey.errors.append("Please enter the correct registration key")
            return False
        #only check if there is a string in self.atomfeed.data, that way users
        #can elect to not enter a atom feed.
        if self.atomfeed.data: 
            if not good_feed(self.atomfeed.data):
                print "data is:" + self.atomfeed.data + ":"
                self.atomfeed.errors.append("Bad atom feed, please try again")
                return False
        
        return True

class ProfileForm(RegisterForm):
    
    username = TextField('Username')
    
    #define custom validator to allow user to keep their username and email the same
    #TODO this validate routine users so much of the RegisterForm one
    #fix it to have less code repetition 
    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        
        if current_user.email != self.email.data:
            user = User.query.filter_by(email=self.email.data).first()
            if user:
                self.email.errors.append("Email already registered")
                return False
                
        #only check if there is a string in self.atomfeed.data, that way users
        #can elect to not enter a atom feed.
        if self.atomfeed.data: 
            if not good_feed(self.atomfeed.data):
                print "data is:" + self.atomfeed.data + ":"
                self.atomfeed.errors.append("Bad atom feed, please try again")
                return False
        
        return True

class PostForm(Form):
    title = TextField('Title',
                    validators=[DataRequired(), Length(min=3, max=125)])
    content = TextAreaField('Comment',validators=[DataRequired(), Length(min=3, max=25)])
    
    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            self.username.errors.append("Failed vaildation")
            return False
        return True

class CommentForm(Form):
    comment = TextAreaField('Comment',validators=[DataRequired(), Length(min=3, max=25)])
    
    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            self.username.errors.append("Failed vaildation")
            return False
        return True

blogaggregator/blogaggregator/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template

from blogaggregator.settings import ProdConfig
from blogaggregator.assets import assets
from blogaggregator.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
    gravatar,
)
from blogaggregator import public, user


def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    gravatar.init_app(app)
    gravatar.size = 500
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

blogaggregator/blogaggregator/user/__init__.py
'''The user module.'''

from . import views

blogaggregator/blogaggregator/user/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask.ext.login import login_required
from flask.ext.login import current_user
from sqlalchemy import asc, desc

from blogaggregator.user.forms import PostForm
from blogaggregator.user.forms import CommentForm
from blogaggregator.user.models import Post
from blogaggregator.user.models import User
from blogaggregator.user.models import Comment
from blogaggregator.utils import flash_errors
from blogaggregator.utils import summarise_post
from blogaggregator.utils import check_latest_update
from blogaggregator.database import db

from blogaggregator.user.forms import ProfileForm

from uuid import uuid4

blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")



@blueprint.route("/")
@login_required
def members():
    return render_template("users/members.html")

@blueprint.route("/profile",methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm(request.form)
    if request.method == "GET": #populate registration form with the existing profile
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.registrationkey.data = "DS106TestKey"
        form.atomfeed.data = current_user.atomfeed
        form.password.data = current_user.password

    if form.validate_on_submit():
        current_user.email = form.email.data
        current_user.atomfeed = form.atomfeed.data
        current_user.set_password(form.password.data)
        db.session.commit()
        flash("Profile modified", 'success')
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)
        
    return render_template("users/profile.html",user=current_user, form=form)

@blueprint.route("/addpost/", methods=["GET","POST"])
@login_required
def addpost():
    form = PostForm(request.form)
    if request.method == "GET":  #save current written data in the session TODO do this
        pass 
    
    if request.method == 'POST':
        if form.validate_on_submit:
            content = form.content.data
            summary = summarise_post(content)
            title = form.title.data
            new_post = Post.create(content = content,
                summary = summary,
                title = title,
                user_id=current_user.id,
                atomuuid=str(uuid4()),
                link="")
            check_latest_update(current_user,new_post)
            flash("Thanks for the post.", 'success')
            redirect_url = request.args.get("next") or url_for("user.members")
            return redirect(redirect_url)
        else:
            flash_errors(form)
                
        #~ current_user.last_login=dt.datetime.now()   
        
    
    return render_template("users/addpost.html", form=form)

#TODO move this into the public views!
@blueprint.route("/posts/<username>/<postid>/", methods=["GET"])
def comment(username,postid):
    #~ form = CommentForm(request.form)
    allowedit = False # by default, no edits
    comments_all=db.session.query(Comment).filter(Comment.post_id==postid).order_by(asc(Comment.created_at)).all()
    if not comments_all :
        comments_all=[{'user':'username','content':'No comments yet :('}]
    else:  #check if the last post is byt he current user (for comment edits)
        last_comment_userid=comments_all[-1].user.id        
        if current_user.is_authenticated():
            if last_comment_userid == current_user.id:
                allowedit = True
    post = Post.query.get(postid)
    return render_template('users/comments.html',username=username,post=post,postid=postid,comments_all=comments_all, allowedit=allowedit)
    

# TODO fix, this doesn't also display the commments as it should    
@blueprint.route("/posts/<username>/<postid>/comment/<commentmethod>", methods=["POST","GET"])
@login_required
def makecomment(username,postid,commentmethod):
    #get the post owner user from url input
    post_owner = User.query.filter_by(username=username).first()
    
    
    if commentmethod == 'new':
        form = CommentForm(request.form)
    elif commentmethod == 'edit':
        comment_last=db.session.query(Comment).filter(Comment.post_id==postid).order_by(desc(Comment.created_at)).first()
        # if the current user is the one who made the last comment, allow editing
        if comment_last.user_id == current_user.id:
            old_content=comment_last.content
            row={'comment':old_content}
            form = CommentForm(**row)
        else:
            flash("Sorry you cannot edit this post","warning")
            redirect_url =  url_for('user.comment',username=username, postid=postid)
    else: #invalid var passed to url builder
        redirect_url =  url_for('user.comment',username=username, postid=postid)
        return redirect(redirect_url)
    
    if request.method == "GET":
        pass
    if request.method == "POST":
        if form.validate_on_submit:
            comment = form.comment.data
            if commentmethod == 'new':
                new_comment = Comment.create(content=form.comment.data,
                    post_id = postid,
                    user_id = current_user.id)
                
                check_latest_update(post_owner,new_comment)
                #update count on posts
                post=Post.query.filter_by(id = postid).first()
                comment_count=db.session.query(Comment).filter(Comment.post_id==postid).order_by(asc(Comment.created_at)).count()
                post.comment_count=comment_count
                flash("Thanks for making a comment.", 'success')
            elif commentmethod == 'edit':
                comment_last.content = comment
                check_latest_update(post_owner,comment_last)
                flash("Comment edited.", 'success')
            db.session.commit()
            
            redirect_url =  url_for('user.comment',username=username, postid=postid)
            return redirect(redirect_url)
        else:
            flash_errors(form)
            redirect_url =  url_for('user.comment',username=username, postid=postid)
            return redirect(redirect_url)
    return render_template('users/newcomment.html',form=form)

blogaggregator/blogaggregator/templates/users/addpost.html
{% extends "layout.html" %}
{% block content %}
    
<div id="formdiv" class="boxrounded">
        <form id="sidebar" class="row col-xs-12 form usercard" method="POST" action="" role="form">
            
            <div class="form-group">
                {{form.title.label}}
                {{form.title(placeholder="Title", class_="form-control")}}
            </div>
            
            <div id="commentText" class="form-group">
                <h3>Post</h3>
                {{ form.content(placeholder="Post content
                    ",rows=10, cols=35)|safe }}
            </div>
            
            <div id="submitButton" class="form-group">
                 <input class="btn btn-primary btn-submit" type="submit" value="Submit">
            </div>
        
        </form>
</div>
    
{% endblock %}

blogaggregator/blogaggregator/templates/users/comments.html
<!-- extends layout -->
{% extends "layout.html" %}

{% block content %}
    <div class="col-md-offset-2 col-md-8">
        <div class="commentcard">
       
           <p> </p>
           <h3>{{ post.summary|safe }}</h3>
          <h3>Comments</h3>
          <hr>
          {% for comment in comments_all %}
                <div>
                    <p>{{ comment.content|safe }}</p>
                    <p><b>{{ comment.user.username|capitalize  }}</b></p>
                    <hr>
                </div>
          {% endfor %}
          
        {% if allowedit == True %}
            
            <div>
                <p><a href="{{ url_for('user.makecomment',username=username,postid=postid,commentmethod='edit') }}" class="btn btn-primary btn-large"> Edit last comment &raquo; </a></p>
            </div>
            <p class="smallspace">  </p>
    
          {% endif %}
        {% if current_user and current_user.is_authenticated() %}
          <div>
              <p><a href="{{ url_for('user.makecomment',username=username,postid=postid,commentmethod='new') }}" class="btn btn-primary btn-large"> Make new comment &raquo; </a></p>
          </div>
          <p class="smallspace">  </p>
        {% endif %}
     </div>
    </div>

{% endblock %}

blogaggregator/blogaggregator/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}

blogaggregator/blogaggregator/templates/users/newcomment.html
<!-- extends layout -->
{% extends "layout.html" %}

{% block content  %}
   
      <form id="sidebar" class="col-sm-12 form usercard" method="POST" action="" role="form">
        <h3>Make Comment</h3>
        
        <div class="form-group">
        {{ form.comment(placeholder="Comment?
            ",rows=10, cols=35) }}
        </div>
            
        <div id="submitButton" class="form-group">
            <input class="btn btn-primary btn-submit" type="submit" value="Submit">
        </div>
      </form>

{% endblock %}

blogaggregator/blogaggregator/templates/users/profile.html
{% extends "layout.html" %}
{% block content %}
 <div class="container-narrow usercard">
  
  <h1>{{user.username }}'s profile</h1>
    <br/>
    <form id="registerForm" class="form form-register" method="POST" action="" role="form">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{form.email.label}}
                {{form.email(placeholder="Email", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.atomfeed.label}}
                {{form.atomfeed(placeholder="Atom Feed", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.registrationkey.label}}
                {{form.registrationkey(placeholder="Registration Key", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.password.label}}
                {{form.password(placeholder="Password", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.confirm.label}}
                {{form.confirm(placeholder="Password (again)", class_="form-control")}}
            </div>
            <p><input class="btn btn-default btn-submit" type="submit" value="Modify Profile"></p>
    </form>
    <p><em>Already registered?</em> Click <a href="/">here</a> to login.</p>
</div>
    
{% endblock %}